services:
  web:
    build: .
    container_name: weaponbackend_web
    command: gunicorn weaponpowercloud_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - weapon_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: weaponbackend_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt/live/3.74.228.219:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - weapon_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: weaponbackend_redis
    ports:
      - "6379:6379"
    networks:
      - weapon_network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:

networks:
  weapon_network:
    driver: bridge

