# Generated by Django for custom User model without groups and permissions

from django.db import migrations, models
import django.utils.timezone
import authentication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(help_text='Azure AD Object ID or username claim', max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, help_text='User email address from Azure AD', max_length=254)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('admin', 'Administrator')], default='employee', help_text='User role in the system', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user account is active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='When the user account was created')),
                ('first_name', models.CharField(blank=True, help_text='User first name from Azure AD', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='User last name from Azure AD', max_length=150)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last time user logged in', null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
    ]
