# Generated by Django 5.2.4 on 2025-08-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_group_alter_user_role_usergroup_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_type',
            field=models.CharField(choices=[('regular', 'Regular Email/Password'), ('azure', 'Azure AD SSO')], default='regular', help_text='Authentication type used for this user', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='User email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Azure AD Object ID for Azure users, email for regular users', max_length=255, unique=True),
        ),
    ]
