# Generated by Django 5.2.4 on 2025-08-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='respondent_phone',
            field=models.CharField(blank=True, help_text='Phone for anonymous responses (when respondent is null)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='public_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', help_text='Contact method required for public survey submissions (email or phone)', max_length=5),
        ),
    ]
