# Generated by Django 5.2.4 on 2025-08-02 23:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Unique token string for public access', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration date')),
                ('is_active', models.BooleanField(default=True, help_text='Whether token is active')),
                ('created_by', models.ForeignKey(help_text='User who created this token', on_delete=django.db.models.deletion.CASCADE, related_name='created_tokens', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(help_text='Survey this token provides access to', on_delete=django.db.models.deletion.CASCADE, related_name='public_tokens', to='surveys.survey')),
            ],
            options={
                'verbose_name': 'Public Access Token',
                'verbose_name_plural': 'Public Access Tokens',
                'db_table': 'surveys_public_access_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='surveys_pub_token_de6cbc_idx'), models.Index(fields=['survey'], name='surveys_pub_survey__0d0bfd_idx'), models.Index(fields=['expires_at'], name='surveys_pub_expires_045b1a_idx'), models.Index(fields=['is_active'], name='surveys_pub_is_acti_8abfd3_idx')],
            },
        ),
    ]
