# Generated by Django 5.2 on 2025-08-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_response_respondent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccesstoken',
            name='password',
            field=models.CharField(blank=True, help_text='Password for accessing the survey via this token', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='publicaccesstoken',
            name='restricted_email',
            field=models.EmailField(blank=True, help_text='If set, only this email can use the token', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='publicaccesstoken',
            name='restricted_phone',
            field=models.CharField(blank=True, help_text='If set, only this phone number can use the token', max_length=20, null=True),
        ),
    ]
