# Generated by Django 5.2.4 on 2025-08-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_create_shared_groups_table'),
        ('surveys', '0002_initial'),
    ]

    operations = [
    ]
