# Generated by Django 5.2.4 on 2025-08-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_publicaccesstoken'),
    ]

    operations = [
    ]
