# Generated by Django 5.2.4 on 2025-08-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20250803_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='respondent_email',
            field=models.EmailField(blank=True, help_text='Email for anonymous responses (when respondent is null)', max_length=254, null=True),
        ),
    ]
