# Generated by Django 5.2.4 on 2025-08-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_add_missing_shared_with_groups_table'),
        ('surveys', '0003_merge_0002_create_shared_groups_table_0002_initial'),
    ]

    operations = [
    ]
