# Generated by Django 5.2.4 on 2025-08-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_ensure_shared_with_groups_table'),
        ('surveys', '0004_merge_20250808_0506'),
    ]

    operations = [
    ]
