# Generated by Django 5.2 on 2025-08-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_convert_restricted_fields_to_arrays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicaccesstoken',
            name='restricted_email',
            field=models.TextField(blank=True, help_text='Comma-separated list of emails that can use the token', null=True),
        ),
        migrations.AlterField(
            model_name='publicaccesstoken',
            name='restricted_phone',
            field=models.TextField(blank=True, help_text='Comma-separated list of phone numbers that can use the token', null=True),
        ),
    ]
