# Generated by Django 5.2.4 on 2025-08-03 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_add_respondent_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['survey', 'respondent_email'], name='surveys_res_survey__267598_idx'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('respondent__isnull', False)), fields=('survey', 'respondent'), name='unique_survey_respondent'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(condition=models.Q(('respondent__isnull', True), ('respondent_email__isnull', False)), fields=('survey', 'respondent_email'), name='unique_survey_respondent_email'),
        ),
    ]
