# Generated by Django 5.2.4 on 2025-08-07 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_add_unique_response_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Survey end date/time. If not set, survey runs indefinitely.', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Survey start date/time. If not set, survey starts immediately when created.', null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Creator & shared list'), ('AUTH', 'All authenticated users'), ('PUBLIC', 'Everyone, even anonymous')], default='AUTH', help_text='Survey visibility level', max_length=7),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['start_date'], name='surveys_sur_start_d_67747e_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['end_date'], name='surveys_sur_end_dat_9404d7_idx'),
        ),
    ]
