# Generated by Django 5.2 on 2025-08-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20250811_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', help_text='Survey status - draft surveys can be edited, submitted surveys are final', max_length=10),
        ),
    ]
