# Generated by Django 5.2.4 on 2025-08-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_group_alter_user_role_usergroup_user_groups'),
        ('surveys', '0006_survey_end_date_survey_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this survey', related_name='shared_surveys', to='authentication.group'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Creator & shared list'), ('AUTH', 'All authenticated users'), ('PUBLIC', 'Everyone, even anonymous'), ('GROUPS', 'Shared with specific groups')], default='AUTH', help_text='Survey visibility level', max_length=8),
        ),
    ]
