# Generated by Django 5.2.4 on 2025-08-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_auth_type_alter_user_email_alter_user_username'),
        ('surveys', '0007_survey_shared_with_groups_alter_survey_visibility'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='response',
            name='unique_survey_respondent',
        ),
        migrations.RemoveConstraint(
            model_name='response',
            name='unique_survey_respondent_email',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='surveys_ans_respons_798aa9_idx',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='surveys_ans_questio_9e381c_idx',
        ),
        migrations.RemoveIndex(
            model_name='publicaccesstoken',
            name='surveys_pub_token_de6cbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='publicaccesstoken',
            name='surveys_pub_survey__0d0bfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='publicaccesstoken',
            name='surveys_pub_expires_045b1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='publicaccesstoken',
            name='surveys_pub_is_acti_8abfd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='surveys_que_survey__1096d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='surveys_que_order_bb46a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='surveys_que_text_ha_5cd9a1_idx',
        ),
        migrations.RemoveIndex(
            model_name='response',
            name='surveys_res_survey__bb39ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='response',
            name='surveys_res_respond_92ba40_idx',
        ),
        migrations.RemoveIndex(
            model_name='response',
            name='surveys_res_submitt_95b24b_idx',
        ),
        migrations.RemoveIndex(
            model_name='response',
            name='surveys_res_survey__267598_idx',
        ),
        migrations.RemoveIndex(
            model_name='survey',
            name='surveys_sur_creator_d5c7e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='survey',
            name='surveys_sur_visibil_4cf541_idx',
        ),
        migrations.RemoveIndex(
            model_name='survey',
            name='surveys_sur_is_acti_dc120c_idx',
        ),
        migrations.RemoveIndex(
            model_name='survey',
            name='surveys_sur_created_9f7bbb_idx',
        ),
        migrations.RemoveIndex(
            model_name='survey',
            name='surveys_sur_deleted_8e8ae0_idx',
        ),
        migrations.RemoveIndex(
            model_name='survey',
            name='surveys_sur_title_h_65f9d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='survey',
            name='surveys_sur_start_d_67747e_idx',
        ),
        migrations.RemoveIndex(
            model_name='survey',
            name='surveys_sur_end_dat_9404d7_idx',
        ),
        migrations.AlterField(
            model_name='survey',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this survey', related_name='shared_surveys_groups', to='authentication.group'),
        ),
    ]
