# Generated by Django 5.2.4 on 2025-08-02 19:38

import Files_Endpoints.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Files_Endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='data_blob',
            field=Files_Endpoints.models.EncryptedBinaryField(help_text='Binary file data stored in database (encrypted)'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=Files_Endpoints.models.EncryptedCharField(help_text='Original filename (encrypted)', max_length=255),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=Files_Endpoints.models.EncryptedCharField(help_text='Folder name (encrypted)', max_length=255),
        ),
    ]
