# Generated by Django 5.2.4 on 2025-08-01 15:34

import django.db.models.deletion
import django.utils.timezone
import news_service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_arabic', news_service.models.EncryptedCharField(help_text='News title in Arabic', max_length=500, verbose_name='Arabic Title')),
                ('title_english', news_service.models.EncryptedCharField(help_text='News title in English', max_length=500, verbose_name='English Title')),
                ('description', news_service.models.EncryptedTextField(help_text='Detailed description of the news item', verbose_name='Description')),
                ('main_image', news_service.models.EncryptedBinaryField(blank=True, help_text='Primary image for the news item', null=True, verbose_name='Main Image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this news item is active and visible', verbose_name='Active')),
                ('category', models.CharField(choices=[('military', 'Military Achievement'), ('technology', 'Technology Achievement'), ('training', 'Training Achievement'), ('partnership', 'Partnership Achievement'), ('award', 'Award/Recognition'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('achievement_date', models.DateField(blank=True, help_text='When the achievement occurred', null=True, verbose_name='Achievement Date')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-achievement_date', '-date'],
            },
        ),
        migrations.CreateModel(
            name='CardsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_arabic', news_service.models.EncryptedCharField(help_text='News title in Arabic', max_length=500, verbose_name='Arabic Title')),
                ('title_english', news_service.models.EncryptedCharField(help_text='News title in English', max_length=500, verbose_name='English Title')),
                ('description', news_service.models.EncryptedTextField(help_text='Detailed description of the news item', verbose_name='Description')),
                ('main_image', news_service.models.EncryptedBinaryField(blank=True, help_text='Primary image for the news item', null=True, verbose_name='Main Image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this news item is active and visible', verbose_name='Active')),
                ('category', models.CharField(choices=[('general', 'General News'), ('military', 'Military News'), ('technology', 'Technology News'), ('training', 'Training News'), ('announcement', 'Announcement'), ('press_release', 'Press Release'), ('event', 'Event'), ('other', 'Other')], default='general', max_length=20, verbose_name='Category')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured news', verbose_name='Featured')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View Count')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Cards News',
                'verbose_name_plural': 'Cards News',
                'ordering': ['-is_featured', '-date'],
            },
        ),
        migrations.CreateModel(
            name='SliderNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_arabic', news_service.models.EncryptedCharField(help_text='News title in Arabic', max_length=500, verbose_name='Arabic Title')),
                ('title_english', news_service.models.EncryptedCharField(help_text='News title in English', max_length=500, verbose_name='English Title')),
                ('description', news_service.models.EncryptedTextField(help_text='Detailed description of the news item', verbose_name='Description')),
                ('main_image', news_service.models.EncryptedBinaryField(blank=True, help_text='Primary image for the news item', null=True, verbose_name='Main Image')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this news item is active and visible', verbose_name='Active')),
                ('priority', models.IntegerField(default=0, help_text='Higher numbers appear first in slider (0-100)', verbose_name='Priority')),
                ('display_duration', models.IntegerField(default=5, help_text='How long to display this slide', verbose_name='Display Duration (seconds)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Slider News',
                'verbose_name_plural': 'Slider News',
                'ordering': ['-priority', '-date'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', news_service.models.EncryptedBinaryField(verbose_name='Image Data')),
                ('caption', news_service.models.EncryptedCharField(blank=True, max_length=200, verbose_name='Caption')),
                ('alt_text', news_service.models.EncryptedCharField(blank=True, max_length=200, verbose_name='Alt Text')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news_service.achievement')),
                ('cards_news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news_service.cardsnews')),
                ('slider_news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news_service.slidernews')),
            ],
            options={
                'verbose_name': 'News Image',
                'verbose_name_plural': 'News Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
