# Generated by Django 5.2.4 on 2025-08-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('military', 'Military Achievement'), ('technology', 'Technology Achievement'), ('training', 'Training Achievement'), ('partnership', 'Partnership Achievement'), ('award', 'Award/Recognition'), ('general', 'General Achievement'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category'),
        ),
    ]
